version: '3.8'

services:
  arxiv-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    # For published images, use:
    # image: ghcr.io/tejas242/arxiv-mcp:latest
    # For development images, use:
    # image: ghcr.io/tejas242/arxiv-mcp:dev
    container_name: arxiv-mcp-server
    restart: unless-stopped
    
    # Environment variables - customize as needed
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      # Optional: Customize server behavior
      # - ARXIV_MCP_ENVIRONMENT=production
      # - ARXIV_MCP_LOG_LEVEL=INFO
      # - ARXIV_MCP_API_TIMEOUT=30
      # - ARXIV_MCP_API_MAX_RETRIES=3
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a simple web interface or monitoring
  # Uncomment if you want to add additional services
  # monitoring:
  #   image: prom/prometheus:latest
  #   container_name: arxiv-mcp-monitoring
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   depends_on:
  #     - arxiv-mcp
